name: Bug Report
description: Report an error or issue with the content
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report an issue! Please fill out the information below.

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of the repository has the issue?
      options:
        - Documentation/Module Content
        - Example Configuration
        - Resource Links
        - Other
    validations:
      required: true

  - type: dropdown
    id: module
    attributes:
      label: Module (if applicable)
      description: Which module is affected?
      options:
        - Module 0 - Introduction
        - Module 1 - Basics
        - Module 2 - Intermediate
        - Module 3 - Configuration
        - Module 4 - Plugin Management
        - Module 5 - LSP
        - Module 6 - Advanced
        - Module 7 - Workflows
        - Example - Minimal
        - Example - Basic
        - Example - Python Dev
        - Example - Web Dev
        - Not applicable

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear description of the issue
      placeholder: What's wrong? Be as specific as possible.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to...
        2. Try to...
        3. See error...
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
      placeholder: Describe what you expected to happen
    validations:
      required: false

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens?
      placeholder: Describe what actually happened
    validations:
      required: false

  - type: input
    id: location
    attributes:
      label: File/Location
      description: Link or path to the problematic content
      placeholder: docs/01-basics/navigation.md or line number
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment (if relevant)
      description: Your system information
      placeholder: |
        - Neovim version: (run `nvim --version`)
        - OS: macOS/Linux/Windows
        - Example config: minimal/basic/python-dev/web-dev
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might be helpful
      placeholder: Screenshots, error messages, etc.
    validations:
      required: false
